name: regcard
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^2.0.15
  get: ^4.6.6
  provider: ^6.1.2
  connectivity_plus: ^6.1.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  permission_handler: ^11.3.1
  timeago: ^3.7.0
  bot_toast: ^4.1.3
  intl: ^0.20.2
  circular_profile_avatar: ^2.0.5
  path_provider: ^2.1.4
  fluttertoast: ^8.2.8
  photo_view: ^0.15.0
  expandable: ^5.0.1
#  intl_phone_number_input: ^0.7.4
  flutter_keyboard_visibility: ^6.0.0
  pin_code_fields: ^8.0.1
  keyboard_actions: ^4.2.0
  readmore: ^3.0.0
  url_launcher: ^6.3.1
  text_scroll: ^0.2.0
  country_code_picker: ^3.1.0
  country_picker: ^2.0.26
  dotted_border: ^2.1.0
  open_filex: ^4.6.0
  carousel_slider: ^5.0.0
  flutter_slidable: ^3.1.2
  badges: ^3.1.2
  percent_indicator: ^4.2.3
  scroll_to_index: ^3.0.1
  flutter_switch: ^0.3.2
  google_fonts: ^6.2.1
  flutter_widget_from_html: ^0.15.3
  qr_flutter: ^4.1.0
  webview_flutter: ^4.9.0
  share_plus: ^10.1.1
  flutter_timezone: ^3.0.1
  hive: ^2.2.3
  dropdown_button2: ^2.3.9
  file_saver: ^0.2.14
  pull_to_refresh_flutter3: ^2.0.2
#  syncfusion_flutter_pdfviewer: ^27.2.2
  syncfusion_flutter_core: ^27.2.2
  device_info_plus: ^10.1.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4
  signalr_core: ^1.1.2
  http: ^1.2.2
  smooth_page_indicator: ^1.2.0+3
  file_picker: ^8.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.png"
  remove_alpha_ios: true

dependency_overrides:
  lints: ^4.0.0
  web: ^0.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


#  fonts:
#    - family: InterRegular
#      fonts:
#        - asset: assets/fonts/Inter-Regular.ttf
#    - family: InterBold
#      fonts:
#        - asset: assets/fonts/Inter-Bold.ttf
#    - family: InterMedium
#      fonts:
#        - asset: assets/fonts/Inter-Medium.ttf
#    - family: InterSemiBold
#      fonts:
#        - asset: assets/fonts/Inter-SemiBold.ttf

