class LocalizationMap {
  static Map<String, String> get codesEN => {
        "email_is_required": "Email is required",
        "add_picture_optional": "Add Picture (Optional)",
        "biometrics": "Biometrics",
        "inActive": "Inactive",
        "active": "Active",
        "contact_us": "Contact Us",
        "next": "Next",
        "1_hour": "1 hour",
        "1_day": "1 Day",
        "1_week": "1 Week",
        "admin_support": "Admin Support",
        "accepted": "Accepted",
        "set_regcard_sharing_expiration": "Set Regcard Sharing Expiration",
        "pending": "Pending",
        "reject": "Reject",
        "no_payment_history": "No payment history",
        "no_payment_history_desc": "No payment history has been found yet.",
        "accept": "Accept",
        "payment_contributions": "Payment Contributions",
        "you": "You",
        "paid_by": "Paid by:",
        "expense_details": "Expense Details",
        "payment_history": "Payment History",
        "my_payments": "My Payments",
        "other_payments": "Other Payments",
        "add_picture_optional_des": "Add Picture in PNG, JPG Format",
        "split_payments_with_ease": "Split payments with ease!",
        "space_cannot_be_allowed": "Space cannot be allowed",
        "Please_describe_your_issue_or_question":
            "Please describe your issue or question",
        "share_profile_updated_successfully":
            "Share profile updated successfully",
        "login": "Login",
        "add_members": "Add Members",
        "select_all": "Select All",
        "amount": "Amount",
        "enter_amount": "Enter amount",
        "enter_title": "Enter title",
        "choose_date": "Choose Date",
        "add_expense": "Add Expense",
        "create_your_first_split_payment_to_share_costs_seamlessly":
            "Create your first split payment to share costs seamlessly.",
        "please_enter_your_doc_name": "Please enter your doc name",
        "please_describe_your_issue_and_question":
            "Please describe your issue and question",
        "split_payments": "Split Payments",
        "personalized_updated_successfully":
            "Personalized updated successfully",
        "please_provide_a_reason_for_deleting_an_account":
            "Please provide a reason for deleting an account",
        "field_required": "Field required",
        "foodie": "Foodie",
        "no_alcohol": "No Alcohol",
        "no_pork": "No Pork",
        "vegetarian": "Vegetarian",
        "click_me": "Click me",
        "preferences_updated_successfully": "Preferences updated successfully",
        "please_enter_your_email_address": "Please enter your email address",
        "enter_a_valid_email": "Enter a valid email",
        "emojis_are_not_allowed_in_email_addresses":
            "Emojis are not allowed in the email addresses",
        "please_enter_otp": "Please enter OTP",
        "invalid_otp": "Invalid OTP",
        "please_enter_your_password": "Please enter your password",
        "password_limit": "Minimum 6 digits required",
        "password_should_contain_at_least_eight_character":
            "Password should contain at least 8 character",
        "password_should_contain_at_least_six_character":
            "Password should contain at least  6 character",
        "please_enter_password": "Please enter your password",
        "password_should_be_alphanumeric": "Password should be alphanumeric",
        "password_should_have_capital_alphabet":
            "Password should have a capital alphabet",
        "password_should_1_special_character":
            "Password should have 1 special character",
        "please_enter_your_confirm_password":
            "Please enter your confirm password",
        "re_enter_your_password": "Reenter your password",
        "password_does_not_match": "Password does not match",
        "please_enter_name": "Please enter name",
        "invalid_name": "Invalid name",
        "please_enter_your_first_name": "Please enter your first name",
        "please_enter_your_last_name": "Please enter your last name",
        "field_cant_be_empty": "Field can't be empty",
        "press_again_to_exit": "Press again to exit",
        "connection_restored": "Connection Restored",
        "uh_oh": "Uh Oh!",
        "no_internet_connection": "No Internet Connection",
        "retry": "Retry",
        "email": "Email",
        "email_address": "Email Address",
        "password": "Password",
        "forgot_password?": "Forgot Password?",
        "forgot_password": "Forgot Password",
        "proceed": "Proceed",
        "forgot_password_desc":
            "Add your email and we will send a mail to change your password.",
        "create_an_account": "Create an account",
        "sign_in": "Sign in",
        "log_in": "Log In",
        "we_will_send_an_otp_verification_to_you":
            "We will send an OTP Verification to you",
        "send_me_the_code": "Send me the code",
        "confirm_your_email": "Confirm your email",
        "enter_the_code_we_sent_to_the_email_ending":
            "Enter the code we sent to the email ending",
        "didn_t_receive_code?": "Didn't receive code?",
        "resend?": "Resend?",
        "verify": "Verify",
        "otp_sent_to_your_email": "OTP sent to your email",
        "enter_your_update_password": "Enter your Update Password",
        "must_include_letters_numbers_and_symbol":
            "must include letters, numbers and symbol",
        "confirm_password": "Confirm Password",
        "update": "Update",
        "congratulations": "Congratulations",
        "your_password_has_been_updated_successfully":
            "Your password has been updated successfully.",
        "purchased": "Purchased",
        "profile": "Profile",
        "settings": "Settings",
        "oops": "Oops",
        "sign_up": "Sign Up",
        "or": "or",
        "first_Name": "First Name",
        "last_Name": "Last Name",
        "continue": "Continue",
        "search_by_country_name_or_dial_code":
            "Search by country name or dial code",
        "change_password": "Change Password",
        "privacy_policy": "Privacy Policy",
        "delete_account": "Delete Account",
        "logout": "Logout",
        "new_password": "New Password",
        "old_password": "Old Password",
        "delete": "Delete",
        "yes": "Yes",
        "no": "No",
        "are_your_sure_you_want_to_logout": "Are your sure you want to logout",
        "enter_otp_statement": "6- Digit PIN has been sent to your email",
        "enter_otp": "Enter OTP",
        "sec": "sec",
        "resend_code": "Resend code.",
        "are_you_sure_you_want_to_logout": "Are you sure you want to logout?",
        "choose_option": "Choose option",
        "gallery": "Gallery",
        "camera": "Camera",
        "first_name": "First Name",
        "last_name": "Last Name",
        "surname": "Surname",
        "number": "Number",
        "edit_profile": "Edit Profile",
        "your_profile_has_been_created_successfully":
            "Your profile has been created successfully.",
        "edit_your_profile": "Edit your profile",
        "save": "Save",
        "password_change_successfully": "Password is change successfully",
        "password_wrong": "Password is wrong",
        "email_already_exist": "Email Already Exist",
        "regcard": "Regcard",
        "my_regcard": "My Regcard",
        "my_profile": "My Profile",
        "my_records": "My Records",
        "please_enter_old_password": "Please enter old password",
        "please_enter_you_password": "Please enter your password",
        "please_enter_you_business_type": "Please Enter Your Business Type",
        "phone_number": "Phone Number",
        "i_accept_the": "I accept the ",
        "legal_documents": "Legal Documents",
        "terms_and_conditions": "Terms and Conditions",
        'password_reset': 'Password Reset',
        'password_reset_desc': 'Your password has been reset! Sign in again.',
        'signup_congrats_desc':
            'You have successfully sign up to our app, login to proceed further',
        'something_went_wrong': 'Something went wrong',
        "languages": "Languages",
        "please_select_language": "Please select a language to continue",
        "french": "French",
        "english": "English",
        'skip': 'Skip',
        'address': 'Address',
        'city': 'City',
        'add': 'Add',
        'country': 'Country',
        'single': 'Single',
        'married': 'Married',
        'taken': 'Taken',
        'use_contact_details_as_default': 'Use Contact Details as default',
        'billing_details': 'Billing Details',
        'company_name': 'Company Name',
        'take_photo': 'Take Photo',
        'work_position': 'Work Position',
        'select_date': 'Select Date',
        'date_of_birth': 'Date of Birth',
        'upload_your_photo': 'Upload your photo',
        "my_documents": 'My Documents',
        "family_documents": 'Family Documents',
        "additional_documents": 'Additional Documents',
        "my_preferences": 'My Preferences',
        "my_preferences_desc":
            'In order to facilitate your reception, you can tell us your preferences for the stay (you can fill in this part later).',
        "upload_your_passport_or_id": 'Upload your Passport or ID',
        "family": 'Family',
        "no_kids": 'No Kids',
        "kids": 'Kids',
        "pets": 'Pets',
        "edit": 'Edit',
        "which_method_you_want_to_choose": 'Which method you want to choose?',
        "document_name": 'Document Name',
        "fix_amount": 'Fix Amount',
        "percentage": 'Percentage',
        "enter_email_or_username": 'Enter email or username',
        "who_paid": 'Who paid?',
        "equally": 'Equally',
        "enter_contribution": 'Enter contribution',
        "custom": 'Custom',
        "how_do_you_want_to_split": 'How do you want to split?',
        "record_name": 'Record Name',
        "add_document": 'Add Document',
        "add_documents": 'Add Documents',
        'you_can_add_your_documents_any_time':
            'You can add your documents any time',
        "add_document_desc": 'Add document in JPG, PNG and PDF format',
        "number_of_kids_sex": 'Number of Kids, sex',
        "smoker": "Smoker",
        "non_smoker": "Non Smoker",
        "health_problem_statement":
            "Would you like to inform of any problem(s) of health so that he can adapt your stay accordingly?",
        "write_here": "Write here...",
        "do_you_have_any_allergies?": "Do you have any allergies?",
        "do_you_have_any_mobility_problems?":
            "Do you have any mobility problems?",
        "foot_size": "Foot Size",
        "clothe_size": "Clothe Size",
        "personalized": "Personalized",
        "what_is_the_ideal_temperature_for_your_room?":
            "What is the ideal temperature for your room?",
        "pescatarian": "Pescatarian",
        "what_types_of_gastronomy_do_you_like?":
            "What types of gastronomy do you like?",
        "the_local_gastronomy": "The local gastronomy",
        "the_gastronomy_of_your_country": "The gastronomy of your country",
        "You_have_no_culinary_references": "You have no culinary references",
        "italian": "Italian",
        "japanese": "Japanese",
        "bistro": "Bistro",
        "brewery": "Brewery",
        "gastronomic": "Gastronomic",
        "animated": "Animated",
        "branch": "Branch",
        "cabaret": "Cabaret",
        "cozy": "Cozy",
        "dancing": "Dancing",
        "discreet": "Discreet",
        "family_restaurant": "Family restaurant",
        "what_type_of_activity_will_the_hotelier_be_able_to_advise":
            "What type of activity(ies) will the hotelier be able to advise?",
        "museums_and_monuments": "Museums and monuments",
        "movie_theater": "Movie theater",
        "gigs": "Gigs",
        "theater": "Theater",
        "shopping": "Shopping",
        "night_club": "Night Club",
        "parks_and_outdoors": "Parks and outdoors",
        "amusement_parks": "Amusement parks",
        "exhibitions": "Exhibitions",
        "festival": "Festival",
        "trade_shows_and_fairs": "Trade shows and fairs",
        "sports": "Sports",
        "done": "Done",
        "complete_profile_statement":
            "Your profile has been completed successfully. You can always update your data.",
        "welcome": "Welcome ",
        "explore_what_happening_around_the_world":
            "Explore what’s happening around the world",
        "your_profile": "Your Profile",
        "what_on": "What's on",
        "see_all": "See all",
        "connect_with_members": "Connect with members",
        'explore': 'Explore',
        'home': 'Home',
        'my_RegCard': 'My Regcard',
        'account': 'Account',
        'notifications': 'Notifications',
        'inbox': 'Inbox',
        'close': 'Close',
        'block': 'Block',
        'unblock': 'Unblock',
        'report': 'Report',
        'cancel': 'Cancel',
        'submit': 'Submit',
        'type_a_message': 'Type a message',
        'block_member_desc': 'We won’t tell them you blocked them.',
        'block_member': 'Block member',
        'unblock_member': 'Unblock member',
        'unblock_member_desc': 'Are you sure you want to unblock this user?',
        'block_contact_desc': 'Blocked contact. Unblock to chat.',
        'member_blocked': 'Member Blocked',
        'member_unblocked': 'Member Unblocked',
        'report_submitted': 'Report Submitted',
        'report_submitted_desc':
            'Thanks for submitting the report, We will get back to you as soon as possible.',
        'anything_to_report': 'Anything to report?',
        'member_blocked_desc':
            'The member has been blocked successfully, we won’t tell them you blocked them.',
        'member_unblocked_desc':
            'The member has been unblocked successfully, we won’t tell them you unblocked them.',
        'travel_guide': 'Travel Guide',
        'no_records': 'No Records',
        'connection_accepted': 'Connection Accepted',
        'document': 'Document',
        'my_regcard_documents': 'My Regcard Documents',
        'my_regcard_doc_desc':
            'You can Add your Passport, ID, Driver’s license and Visas also you can add Additional Documents.',
        'no_records_desc': 'You can add record by clicking the button Below.',
        'add_records': 'Add Records',
        "sharing": "Sharing",
        "invite_friend": "Invite Friends",
        "connections": "Connections",
        "help": "Help",
        'edit_record': 'Edit',
        'delete_record': 'Delete',
        "rights_reserve_statement": "All rights reserved Regcard",
        "current_password": "Current Password",
        "chat_replies": "Chat Replies",
        "connection_request": "Connection Request",
        "news_article_uploaded": "News , articles uploaded",
        "sharing_history": "Sharing History",
        "sharing_request_to_confirm": "Sharing Request to confirm",
        "invite": "Invite",
        "share_link_to_invite": "Share link to invite your friends.",
        "share_link_statement":
            "I’m proposing you as a new member of Regcard – use the link below to get started. My membership details will be linked, to show that I support your application.",
        "share_link": "link of Regcard on app store",
        "share": "Share",
        "delete_acc": "Delete Account",
        "delete_acc_statement":
            "Deleting your account means it cannot be recovered thereafter.",
        "write_reason": "Write reason...",
        "help_statement":
            "Please let us know how we can help. We will get back to you as soon as possible.",
        "my_regcard_document": 'My Regcard Document',
        "manage_settings": 'Manage Settings',
        "share_profile": 'Share Profile',
        "remove": "Remove",
        "select_document_type": "Select Document Type",
        "select_type": "Select Type",
        "add_documents_desc": "Add document in PNG , JPG and PDF format ",
        "scan_me": "Scan me",
        "press_me": "Press me",
        "history": "History",
        "date": "Date",
        "duration": "Duration",
        "time": "Time",
        "creation_date": "Creation Date",
        "creation_time": "Creation Time",
        "total_views": "Total Views",
        "sharing_timeline": "Sharing Timeline",
        "total_times_shared": "Total Times Shared",
        "create_new_regcard": "Create New RegCard",
        "get_a_present_from_regcard_after_sharing_100_times":
            "Get a present from Regcard after sharing 100 times.",
        "shared": "Shared:",
        "times": "times",
        "what_types_of_resturants_do_you_prefer?":
            "What types of restaurants do you prefer to have?",
        "contact_details": "Contact Details",
        "search": "Search",
        "sharing_your_regcard": "Sharing your RegCard",
        "check_again_your_documents": "Check again your documents",
        "copy_link": "Copy Link",
        "link_copied": "Link Copied!",
        "share_regcard": "Share Regcard",
        "records": "Records",
        "mr": "Mr.",
        "mrs": "Mrs.",
        "miss": "Miss.",
        "title": "Title",
        "please_select_the_title": "Please select the title",
        "message": "Message",
        "connect": "Connect",
        "send_request": "Send Request",
        "Are_you_sure_you_want_to_send_this_request":
            "Are you sure you want to send this request?",
        "family_member_name": "Family Member Name",
        "email_not_verified": "Email not verified",
        "logout_successfully": "Logout successfully",
        "please_accept_the_terms_and_conditions":
            "Please accept the Terms and Conditions",
        "verification_code_message": "Verification code has been sent",
        "password_updated": "Your password has been updated!",
        "account_deleted_successfully": "Account deleted Successfully",
        "your_contact_details_is_updated_successfully":
            "Your contact details is updated successfully",
        "your_billing_details_is_updated_successfully":
            "Your billing details is updated successfully",
        "updated_successfully": "Updated Successfully",
        "profile_picture_updated_successfully":
            "Profile picture updated successfully",
        "pull_up_to_load": "Pull Up To Load",
        "load_failed_please_try_again": "Load Failed Please Try Again",
        "release_to_load_more": "Release To Load More",
        "no_more_data": "No More Data",
        "travel_guides": "Travel Guides",
        "no_search": "No Search",
        "no_search_desc":
            "Try adjusting your search to find what you are looking for",
        'record_has_been_deleted_successfully':
            'Record has been deleted successfully.',
        "document_has_been_deleted_successfully":
            'Document has been deleted successfully',
        "no_new_notifications": "No notifications found",
        "no_new_notifications_desc":
            "We’ll notify you whenever you get any new notifications",
        "image_cropper": "Image Cropper",
        "please_give_the_credentials": "Please give the credentials",
        "loading": "Loading...",
        "please_select_and_add_members": "Please select and add members",
        "please_enter_your_amount": "Please enter your amount",
        "please_enter_title": "Please enter title",
        'no_member_search_desc': 'No Member found with this name',
        'no_connections': 'No connections',
        'no_connections_found': 'No connections found',
        'saved_to_downloads_successfully': 'saved to downloads successfully.',
        'failed_to_download_file': 'Failed to download file.',
        'no_chats_found': 'No chats found',
        'no_chats': 'No chats',
        'please_enter_bank_name': 'Please enter bank name',
        'chat_deleted_successfully': 'Chat deleted successfully',
        'no_history': 'No history',
        'no_history_found': 'No history found',
        'please_select_the_payment_method': 'Please select the payment method',
        'please_select_the_payment_split': 'Please select the payment split',
        'please_choose_date': 'Please choose date',
        'amount_must_be_greater_than_zero': 'Amount must be greater than zero',
      };

  static String getTranslatedValues(String key) {
    return codesEN[key] ?? "Text not found";
  }
}
